version: '3.8'

services:
  motolocadora-db:
    image: postgres:15
    container_name: motolocadora-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: motolocadora
    ports:
      - "5432:5432"
    volumes:
      - motolocadora-db-data:/var/lib/postgresql/data
    networks:
      - motolocadora-network

  motolocadora-api:
    build:
      context: .
      dockerfile: MotoLocadora.Api/Dockerfile
    container_name: motolocadora-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=motolocadora-db;Port=5432;Database=motolocadora;Username=postgres;Password=postgres
    ports:
      - "5000:80"
    depends_on:
      - motolocadora-db
    networks:
      - motolocadora-network

volumes:
  motolocadora-db-data:

networks:
  motolocadora-network:
    driver: bridge
